spring:
  application:
    name: demo
server:
  port: 8081

  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true